id: I875498DD
legacy_id: P007105
ocr_import_info:
  bdrc_scan_id: W1KG12717
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T11:34:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:37:41.555813+00:00'
last_modified: 2022-08-31 11:37:46.433099
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12717
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12717
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཕྱག་ཆེན་གྱི་ཟིན་བྲིས་སོགས།
statistics:
  ocr_word_mean_confidence_index: 0.4678958683061819
  ocr_word_median_confidence_index: 0.4000000059604645
quality: null
bases:
  I1KG13009:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13009
      total_pages: 58
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13009.txt
    statistics:
      ocr_word_median_confidence_index: 0.4000000059604645
      ocr_word_mean_confidence_index: 0.4678958683061819
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
