id: I875498DD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T11:34:49+00:00'
last_modified: '2022-06-09T04:56:33.240387+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG12717
  title: ཕྱག་ཆེན་གྱི་ཟིན་བྲིས་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4F83:
      image_group_id: I1KG13009
      title: Volume 1 of phyag chen gyi zin bris sogs/
      total_pages: 58
      order: 1
      base_file: 4F83.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
