id: P007105
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG12717
  title: ཕྱག་ཆེན་གྱི་ཟིན་བྲིས་སོགས།
  author: ''
  volumes:
    b2397f0479cf44fbaa2f120e1c706ffc:
      image_group_id: I1KG13009
      title: Volume 1 of phyag chen gyi zin bris sogs/
      volume_number: 1
      total_pages: 58
      base_file: v001.txt
