id: P007105
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12717
  title: ཕྱག་ཆེན་གྱི་ཟིན་བྲིས་སོགས།
  author: ''
  volumes:
    44451bf716cb4b079b3ca4f79a526f8c:
      image_group_id: I1KG13009
      title: ''
      volume_number: 1
      total_pages: 58
ebook_metadata:
  title: ཕྱག་ཆེན་གྱི་ཟིན་བྲིས་སོགས།
  author: ''
  sku: P007105
  cover: cover.jpg
  layers:
  - pagination
